# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181215_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovies',
            name='movie_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='imdbID'),
        ),
    ]
